### ISSUE TITLE
gigasecond_test.go should be improved

### ISSUE THREAD

**Issue by dchapes** [exercism/xgo#110]
People read the test and blindly make a silly `1e18` constant. Instead the first test should do something like `if time.Duration(Gigasecond) == 1e9 * time.Second`. The cast allows them to use a typed or untyped constant any way they want as long as it is convertible to a `time.Duration` and has the correct value. E.g. `const Gigasecond = 1e18`, `const Gigasecond float64 = 1e18`, `const Gigasecond = 1e12 * time.Millisecond`, etc would all pass.

The second test is also poor. Some people look at it and try to implement `AddGigasecond` using `time.Unix`. Instead it should do something that verifies that time's location hasn't been mucked with.

**Comment by kotp** [comment]
Is this resolved, with the merged PR?

**Comment by kytrinyx** [comment]
Oh, yepp. Thanks!
