### ISSUE TITLE
.travis.yml needs an update

### ISSUE THREAD

**Issue by soniakeys** [exercism/xgo#131]
I think the Go developers aren't going to maintain the "release" tag anymore.  (Git might not handle moving a tag to a new commit the way Mercurial did.)  So I think we'll have to maintain two numbered releases (which currently should be 1.3.3 and 1.4.1) in addition to tip.

update:  Oh wait, I see we weren't even using "release".  And it looks like gvm is smart enough to take the latest point release.  Anyway, it's time for a version update.  should be 1.3 and 1.4

**Comment by kytrinyx** [comment]
I pushed it to a branch to give travis a chance to build it before it goes to master (in case I screwed it up).

**Comment by soniakeys** [comment]
Ah thanks.  I know, almost silly to file an issue but I had thought of this and then forgotten a couple of times already.  I was busy today when I was reminded of it again and didn't want to take time to mess with it so I just filed the issue.

**Comment by soniakeys** [comment]
hm :/  I don't understand...  Now it looks like that didn't pull the point releases.  Do we have to say 1.3.3 and 1.4.1?

**Comment by kytrinyx** [comment]
Maybe we do, I'll try that!

**Comment by soniakeys** [comment]
Yeah, this isn't our fault.  Travis has changed they way they select versions.  Compare the last two build logs.  They were using "gvm" and are now using "gimme".  So maybe before gvm would pick the latest point release but now it has to be specified explicity for gimme.

**Comment by kytrinyx** [comment]
Cool, I'll update the PR

**Comment by soniakeys** [comment]
LGTM

**Comment by soniakeys** [comment]
Fixed with PR https://github.com/exercism/xgo/pull/132
