### ISSUE TITLE
go test on clock fails on TestVersion

### ISSUE THREAD

**Issue by ariddell** [exercism/xgo#135]
```
± go test
# _/home/ar/work/exercism/go/clock
./clock_test.go:32: undefined: TestVersion
./clock_test.go:33: undefined: TestVersion
FAIL	_/home/ar/work/exercism/go/clock [build failed]
```
go 1.4rc2

**Comment by ariddell** [comment]
Oops. I didn't realize I needed to set `TestVersion`. Does this need to be added to the README or elsewhere?

**Comment by soniakeys** [comment]
Mm, the appropriate place to possibly mention it would be the Go help page.  This page doesn't mention TestVersion explicity, but it does cover the typical steps to solving an exercise -- reading the compile errors, reading the test program, puzzling out how to get the program to compile.  In the case of TestVersion the compiler tells you it's not defined, the required value in the test program is pretty easy to spot, ... it's kind of part of the exercise.
