### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#145]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by tejasbubane** [comment]
@pminten I am a go newbie and the first error I see after running `go test` is `undefined: TestVersion`. And I don't know what it is. I check the tests and declare `var TestVersion` like 1 or 2 to just make the error go away. Can you please explain about this as well?

**Comment by pminten** [comment]
Good point, @tejasbubane.

I think we need some discussion on this. There are three options here, though we could do multiple or all of them.

1. Document testVersion in SETUP.md
2. Document testVersion in the Go track help page.
3. For exercises requiring testVersion always supply a stub file with testVersion.

I'm inclined to prefer option 3 since it's easiest for the user. It would however force us to implement #97 for more exercises.

@kytrinyx, @soniakeys, what do you think?

**Comment by kytrinyx** [comment]
I think 3 makes a lot of sense here. Since the testVersion is more about book-keeping than about understanding Go I'd rather not have to make people think too hard about it.

I'll open a separate issue that lists each of the exercises that need a stub file.

**Comment by soniakeys** [comment]
I wanted a stub file early, but then I warmed to figuring out the API as part of the solving process.  What if we had the stub file on some of the earlier exercises to help people get started, and maybe on some others where it makes sense for some reason, but necessarily for all exercises?  Maybe after a few exercises with the exact API to implement, the stub file could have the test version but a comment saying you're on you own to figure out the API.  Then for some later exercises we wouldn't bother with the stub file.

I'm in favor of 2, documenting TestVersion on the track help page no matter what.

**Comment by kytrinyx** [comment]
Yeah, I think it makes sense to have a stub file early on and/or in special cases, and not have it later.

> I'm in favor of 2, documenting TestVersion on the track help page no matter what.

Yes, I agree.
