### ISSUE TITLE
Meetup - 5th Monday

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#151]
There is an interesting edge case in the meetup problem:
some months have five Mondays.

March of 2015 has five Mondays (the fifth being March 30th), whereas
February of 2015 does not, and so should produce an error.

------

Thanks, @JKesMc9tqIQe9M for pointing out the edge case.
See [exercism.io#2142](https://github.com/exercism/exercism.io/issues/2142).

**Comment by pminten** [comment]
There's a bit of an issue with the example version of meetup in various test suites that they only test for valid inputs. In the Elixir version this didn't turn out to be a problem due to it deferring to Erlang's stdlib and Erlang throwing an error on invalid input. For go this will be somewhat more difficult and it's likely to break any user submission.

I've looked through the biggest tracks (ruby, clojure, haskell, javascript) and none of them actually tests for failures. In fact in the Haskell and Go tracks it's downright impossible to signal a failure with the current required API.

So I'd like to ask, do we consider dealing with input to be a required element of the meetup exercise?

**Comment by soniakeys** [comment]
Interesting.  The Go test program requires the solver to define a `WeekSchedule` type and then define six identifiers of type WeekSchedule for the first..fourth, teenth, and last weeks.  There is currently no requirement to define an identifier for the fifth or any other week (pre-teenth?  next to last?)  The test program calls the solver's function with these identifiers but has no good way to generate any ... oh wait, testing/quick.Value.  You know, I'd never used testing/quick before.  So, some ideas,

1.  I think it's okay the way it is.  The readme doesn't mention fifth week as a case that needs to be supported.  The Go test program specifies six cases which are defined for all months.  There is no error handling requirement.  It leaves the exercise more purely one of puzzling out the date arithmetic.

2.  The test program could be changed to do fifth week too.  To handle months without the day in the fifth week, the test program would need to specify that `MeetupDay` return a specified value such as 0 or -1, the value of a specified identifier (letting the solver pick the exact value), an additional `ok` value, or an additional error value.

3.  Untried, but I think we could use quick.Value to generate an invalid `WeekSchedule` value and test that the solver's `MeetupDay` function returns an error for unspecified values of WeekSchedule.

4.  We could do 3 and still not support the fifth week.

5.  We could leave the basic exercise about as it is, but add bonus requirements (using build tags, as done with another exercise or two.)

6. This seems a good candidate for standard test cases in x-common.

**Comment by kytrinyx** [comment]
As someone mentioned in the original issue:

> You can't regularly schedule a meetup on the fifth week of every month because February usually doesn't have a fifth week at all (and no month ever has a full fifth week). It's nonsense to even support "fifth" as an input in the first place. I think that first-fourth, last, teenth are the only scheduling inputs that should be supported.

So it seems like this is basically an irrelevant edge case.

It is interesting in terms of the x-common standard cases though.

**Comment by soniakeys** [comment]
Closed with PR https://github.com/exercism/x-common/pull/124
