### ISSUE TITLE
IDE Suggestion for Go?

### ISSUE THREAD

**Issue by masters3d** [exercism/xgo#164]
Is there a suggested integrated development environment for Go that new students should explore?
http://help.exercism.io/getting-started-with-go.html

**Comment by kytrinyx** [comment]
No, whatever text editor or IDE you usually work with is generally the suggested one.

The workflow for Go is heavily command-line oriented (go test, go vet, golint, etc).

**Comment by masters3d** [comment]
I see. What do you use personally?

**Comment by kytrinyx** [comment]
I use vim

**Comment by masters3d** [comment]
Thanks!

**Comment by pminten** [comment]
I would recommend an editor that does some syntax checking and runs gofmt or goimports on save though. That really smoothes the workflow for me.

For vim there are several packages, findable through google.

I personally use spacemacs with the syntax-checking and go layers enabled, which does gofmt and a quick compile on save.

**Comment by kytrinyx** [comment]
Yeah, I have goimports, go fmt, and syntactic (which does a quick compile on save and highlights compile errors).
