### ISSUE TITLE
Consider creating new Unicode exercise

### ISSUE THREAD

**Issue by soniakeys** [exercism/xgo#200]
Previous discussion at https://github.com/exercism/xgo/issues/195.  The Unicode test case was removed from ledger to limit the scope of that exercise.  But maybe a new exercise could be created around the idea of that test case.  I imagine the original intent of the test case was to show the difference between the bytes of a string and the runes of a string.  This is a good start.  The Rosetta Code task [String length](http://rosettacode.org/wiki/String_length)  introduces the additional concept of the graphemes of a string.  Formatting text in a fixed-pitch font (the subject of ledger) requires yet another width concept ("cell" width, I think) when full-width asian characters are used.  And there's more, but that's probably enough for a good exercise.

**Comment by petertseng** [comment]
Since a new Unicode exercise could be applied to all tracks, I would say this issue should go to x-common. and it's great timing too, since we are talking about that at https://github.com/exercism/x-common/issues/428 ! I'll close this and drop a note in that issue with what I know.
