### ISSUE TITLE
Issue using exercism tool to get the go exercises

### ISSUE THREAD

**Issue by davidsulpy** [exercism/xgo#202]
I'm receiving the following error:
`2015/11/19 14:21:15 error parsing API response - json: cannot unmarshal string into Go value of type []api.SubmissionInfo`

after performing:
`exercism fetch go leap`

**Comment by kytrinyx** [comment]
What does `exercism debug` output?

**Comment by davidsulpy** [comment]
It turns out I had not yet set my api key. It would be nice if the error message had showed me that it was an issue because I had no api key set. Once I ran `exercism configure --key=KEY` and then ran `exercism fetch go leap` everything worked just fine. If I'd followed the directions better I wouldn't've run into this issue, but at least it's still a potentially valid user experience issue.

Thanks for the quick response though!

**Comment by kytrinyx** [comment]
> It turns out I had not yet set my api key.

Aaah, yes we should absolutely give you a good error message for that!

/cc @exercism/cli-committers should we check this at the CLI level, or should the API take care of it and provide a better error message?

**Comment by Tonkpils** [comment]
@kytrinyx I may lean towards both, but if not, the backend definitely needs to at least handle returning error responses as JSON. We could also make the error messages on unmarshal better. The user doesn't really care about the JSON being unable to be parsed. It's simply an error on our end and to provide the debug info as an issue. Thoughts?

**Comment by kytrinyx** [comment]
> I may lean towards checking this at both the CLI and the API level

Agreed.

>  API definitely needs to at least handle returning error responses as JSON

Yeah, definitely.

> We could also make the error messages on unmarshal better.

Yeah, let's do that, as well.

> It's simply an error on our end and to provide the debug info as an issue.

You mean add the output on STDERR but as "extra information" that can be submitted in an issue, if they care to?

**Comment by lcowell** [comment]
I'm thinking it's best to let the api provide us with an error rather than enforcing it at the cli interface. The cli's job is to send up whatever it can, it's the server's job to decide if that good enough.

I think about the discussion here https://github.com/exercism/exercism.io/issues/2607 and the possibility of an anonymous fetch from the cli. We don't really need an api_key to do a fetch and it would mean we only have to make a change in one place if we want to change the rules.

Not needing an api key could be a way of removing barriers to trying exercism out.

**Comment by kytrinyx** [comment]
Oh, right, I forgot about the anonymous fetch thing. That's a better rule in any case.

We still need to make sure the API always sends JSON, not sure how the HTML slipped in there. I'll take a look at this tomorrow.

**Comment by kytrinyx** [comment]
I'm deploying a fix for this right now.
