### ISSUE TITLE
Consider moving excercises to subdirectory

### ISSUE THREAD

**Issue by masters3d** [exercism/xgo#203]
This is not specific to xgo but I noticed that there are a few subdirectories mingling with the exercises that probably should be separated from the actual exercises. Moving them to into a /problems or /exercises or similar subdir could be a solution but this will affect all the tracks. 

bin
docs
error-handling
gen
img

Something to think about.

**Comment by kytrinyx** [comment]
Yeah, it would affect all the tracks (as well as the x-api), but it would actually simplify things, so it could be worth doing.

We'd want to do it all in one fell swoop, so it would take a little bit of coordination.

Things we'll want to think about:

- linting with configlet
- can simplify the config.json to remove the "ignored" key (yay)
- x-api will need to change at least one path (probably more--I'm mid-refactoring to fix that)
- any tracks that implement generators will have to adjust those
- any tracks that implement CI will have to adjust for that
- ... ?

**Comment by kytrinyx** [comment]
There's support for putting all the exercises in a subdirectory named "exercises". I'll submit an issue to each track. See #240.
