### ISSUE TITLE
Tests for triangle can be solved by an empty implementation.

### ISSUE THREAD

**Issue by zeroDivisible** [exercism/xgo#207]
Hi,

I started working on this problem  (`triangle`), only to notice that after I added stubs for entities in my code, all tests passed. Basically, my "solution" was this:

```
package triangle

func KindFromSides(a, b, c float64) Kind {
	return Kind{}
}

type Kind struct {
}

var Equ = Kind{} // equilateral
var Iso = Kind{} // isosceles
var Sca = Kind{} // scalene
var NaT = Kind{} // not a triangle
```

and all of the tests which I ran locally passed. I presume this is incorrect?

**Comment by petertseng** [comment]
Yeah seems like we wouldn't want this to happen.

The fix would be to make sure that no pair within  `{Equ, Iso, Sca, NaT}` are equal to each other, right?

My ETA for a fix isn't for another 36 hours (I will assign myself if I start work), so if someone wants to beat me to it, feel free.

**Comment by soniakeys** [comment]
Peter, yes, I agree that sounds like the fix.
