### ISSUE TITLE
Tests for secret-handshake fails yet correct output

### ISSUE THREAD

**Issue by lynnUg** [exercism/xgo#213]
Hi ,
I'm currently working on the exercism "secret handshake". Input 3 and 19 should have the same output "double blink", "wink" however according to the struct below the output is different. Is test for 3 below correct?
```go
var tests = []struct {
	code int
	h    []string
}{
	{1, []string{"wink"}},
	{2, []string{"double blink"}},
	{4, []string{"close your eyes"}},
	{8, []string{"jump"}},
	{3, []string{"wink", "double blink"}},
	{19, []string{"double blink", "wink"}},
	{31, []string{"jump", "close your eyes", "double blink", "wink"}},
	{0, nil},
	{-1, nil},
	{32, nil},
	{33, []string{"wink"}},
}
```

**Comment by kytrinyx** [comment]
There's a good chance it could be incorrect... I'll take a look this afternoon.

**Comment by kytrinyx** [comment]
Nope, this is correct. The requirement is that if there's a digit in the 16s place (base 2), then the list of commands get reversed.

**Comment by lynnUg** [comment]
Thanks , your right!!!
