### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#231]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by petertseng** [comment]
:white_check_mark: for xgo. we have this test as of https://github.com/exercism/xgo/blob/d895e12bc457dad8c024ad457380ade2a5f55aa9/exercises/triangle/triangle_test.go#L28

**Comment by petertseng** [comment]
Reopening because I think you meant this test should be **removed**. Is that right?

**Comment by masters3d** [comment]
It should be isosceles
https://github.com/exercism/xswift/issues/104

**Comment by petertseng** [comment]
I'm going to give it a bit of time to let discussion settle. It looks like at least https://github.com/exercism/xerlang/issues/85 wanted time to think about it as well. Will monitor the discussions at https://github.com/issues?utf8=%E2%9C%93&q=triangle+is%3Aissue+user%3Aexercism - would maybe be good if the emblazoned tickets would link to a common place to have this discussion?

**Comment by petertseng** [comment]
Thought about it. Triangle inequality explicitly allows equal, so I'm pretty convinced. PR is ready.

**Comment by kytrinyx** [comment]
Agreed, according to wikipedia it's correct. I think we'll see some research on this over the next couple of days, and we can revert/fix if we come to a different conclusion.
