### ISSUE TITLE
Consider re-implementing house to not guide the solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#242]
Right now the test suite suggests that house should have a recursive solution, but it's quite a lot simpler without it. I'd like to leave the door open for a larger variety of approaches to this problem.

**Comment by bordeltabernacle** [comment]
I've just implemented house, and my first reaction was that it was another similar implementation of the basic problem in `twelve_days` and `food-chain`. I agree, recursion is not the simplest solution, but the simpler solution has been tackled earlier in the other two exercises I mentioned, and I quite like that we're being pushed to consider and implement recursion here instead. I think if we're not nudged towards recursion this problem will perhaps feel repetitive. Plus the feeling when recursion clicks is pretty great.

**Comment by petertseng** [comment]
The thing that I do find strange is why does `Embed` have to be exported + tested? It isn't immediately clear what it has to do with the problem at hand, and some people might want to implement it differently. I think I would at the least remove `Embed`.

**Comment by petertseng** [comment]
EBWODP: After removing `Embed`, if people want the recursion suggestion to stay,  let it.
