### ISSUE TITLE
Might help to add a period to the go test instructions

### ISSUE THREAD

**Issue by mrice** [exercism/xgo#247]
This one little thing was a speed bump for me when I was first getting started with the Go exercises.

See PR #246.

When I tried to run the go test command as the instructions told me to, Go complained that it couldn't find the helloworld.go file anywhere in my Go path, which is correct since exercism fetched it into its own home directory. I think it cost me almost an (very distracted by kids) hour and I almost gave up on the exercises. 

As I submit this issue, it could be that I was doing it wrong or overlooked something about exercism but Go's GOPATH is confusing enough for a complete newbie (like me) that this simple period was a big help for me. If I should have just done something different with Go (like override the GOPATH) or configure exercism differently, let me know and I'll revise the PR.

Thanks for an awesome tool and community!

**Comment by kytrinyx** [comment]
Hm, I'm not sure what happened. Exercism should work without having the GOPATH set up.

If I fetch a fresh version of `hello-world` in Go, here's what happens on my machine (exercism is outside my GOPATH).

```
$ rm -rf ~/exercism/go/hello-world
$ exercism fetch go hello-world

Not Submitted:   1 problem
Go (Hello World) /Users/kytrinyx/exercism/go/hello-world

New:             1 problem
Go (Hello World) /Users/kytrinyx/exercism/go/hello-world

unchanged: 0, updated: 0, new: 1

$ cd /Users/kytrinyx/exercism/go/hello-world
$ go test
# _/Users/kytrinyx/exercism/go/hello-world
./hello.go:29: missing return at end of function
FAIL	_/Users/kytrinyx/exercism/go/hello-world [build failed]
```

The dot is not necessary on my machine.

Could you walk me through the reproduction steps for getting Go to complain about the helloworld.go file not being found anywhere in your GOPATH?

**Comment by mrice** [comment]
Crap. You're right. I don't know what I was doing that made it not work, but it was obviously something that seemed important enough to submit a PR. Sorry to waste your time (and thanks much for taking it seriously), but it is fun to be part of your community.

**Comment by kytrinyx** [comment]
No, this is definitely not a waste of time! Sometimes we miss the obvious when we're doing stuff in languages that we're familiar with, and it's very important to find these things and fix them to minimize confusion.

If you ever do figure out what you were doing to make it not work, I'd love to hear about it. We might be able to add something to the documentation or instructions to make it a non-issue.
