### ISSUE TITLE
diffie-hellman: extra commas in signatures in test file

### ISSUE THREAD

**Issue by petertseng** [exercism/xgo#265]
```go
// Step 2:   PublicKey(private, p, *big.Int, g int64) *big.Int
// Step 2.1: NewPair(p, *big.Int, g int64) (private, public *big.Int)
```

the commas between the `p and *big.Int` shouldn't be there

**Comment by petertseng** [comment]
I would have fixed it immediately without bothering to file an issue, but I wanted to wait until I finished my implementation to see if I found any other problems and then batch them all up together (but I didn't find any other problem)

**Comment by kytrinyx** [comment]
Good find!
