### ISSUE TITLE
scrabble-score: replace 'multibillionaire' with 'oxyphenbutazone'

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#270]
The word _multibillionaire_ is too long for the scrabble board. _Oxyphenbutazone_, on the other hand, is legal.

Please verify that there is no test for _multibillionaire_ in the scrabble-score in this track. If the word is included in the test data, then it should be replaced with _oxyphenbutazone_. Remember to check the case (if the original is uppercase, then the replacement also should be).

If multibillionaire isn't used, then this issue can safely be closed.

See https://github.com/exercism/x-common/issues/86

**Comment by kytrinyx** [comment]
This was fixed in https://github.com/exercism/xgo/pull/172 but the original reason we had this was to test that it's case insensitive. Oxyphenbutazone should be uppercased in the test suite.

**Comment by petertseng** [comment]
too bad there's no json file we can just regen our test suite off of, but that's an issue for another day.

**Comment by kytrinyx** [comment]
Yeah, there's a lot of work to be done surveying the test suites and creating generators.
