### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#271]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by petertseng** [comment]
Musing to myself for a bit.

Binary currently has no error handling.

Trinary currently just has OK/not OK: https://github.com/exercism/xgo/blob/master/exercises/trinary/trinary_test.go

Hexadecimal has an interesting error handling, https://github.com/exercism/xgo/blob/master/exercises/hexadecimal/hexadecimal_test.go , checking the specific error case with specific strings ("syntax", "range", "none")

**Comment by petertseng** [comment]
I would favor just ok/not OK as trinary did.

**Comment by kytrinyx** [comment]
I'd also favor ok/not ok.
