### ISSUE TITLE
rna-transcription: don't transcribe both ways

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#272]
I can't remember the history of this, but we ended up with a weird non-biological thing in the RNA transcription exercise, where some test suites also have tests for transcribing from RNA back to DNA. This makes no sense.

If this track does have tests for the reverse transcription, we should remove them, and also simplify the reference solution to match.

If this track doesn't have any tests for RNA->DNA transcription, then this issue can be closed.

See https://github.com/exercism/x-common/issues/148

**Comment by petertseng** [comment]
We are good. Note that our test generator [explicitly calls out the bad tests](https://github.com/exercism/xgo/blob/master/exercises/rna-transcription/example_gen.go#L41) that are [present in the JSON data...!](https://github.com/exercism/x-common/blob/master/rna-transcription.json#L62)

**Comment by kytrinyx** [comment]
That's excellent.
