### ISSUE TITLE
travis: Consider testing 1.6

### ISSUE THREAD

**Issue by petertseng** [exercism/xgo#314]
We have 1.4 and 1.5 listed in the matrix and also tip. Maybe should consider 1.6

Also need to consider how far back we go in our versions. https://golang.org/doc/devel/release.html says they only support one major release at a time (but security support for two major releases), but need to investigate the state of what people are likely to have installed.

**Comment by kytrinyx** [comment]
Yeah, now that 1.6 is out we should test it explicitly.

In my experience upgrading has been painless ever since 1.0 was released. I don't have a strong opinion about how far back we should go. I'm thinking stick with the current + the previous.

**Comment by petertseng** [comment]
Preliminary investigations indicate that the tests seem to pass on all versions going back to 1.1.x (I couldn't get 1.0.3 to work though!) so theoretically we could go waaaay back (which is not necessarily to say that we *should*, but you know).

One small argument against testing ALL THE VERSIONS is that Travis runs only 5 jobs concurrently. Currently we have exactly 5 (1.4.3 on 32-bit, 1.5 and tip on 32-bit and 64-bit). If we were to test all versions possible, we'd get feedback slightly later. On a related note, if we do start testing many versions we should have the ones we care about the most be at the top of the list since they get run first.

**Comment by kytrinyx** [comment]
I didn't know about the 5 concurrent jobs thing. If we add 1.6 in addition to tip and 1.5 we'll be at 6 jobs, so that already tips us past the limit.

**Comment by petertseng** [comment]
Travis does seem to be pretty good at starting up the sixth job when the first of the five finishes though (as opposed to waiting until the fifth one finishes), so it shouldn't be so terrible. I definitely did not feel like even https://travis-ci.org/exercism/xgo/builds/123735373 was too slow since each of our jobs is fast (~ a minute).

Otherwise someone might have argued "Well if we're going to have six jobs, might as well have ten so that the second batch isn't underutilised"...

**Comment by kytrinyx** [comment]
Right, let's try to not exceed 10, and put 1.4 on the allow failures. I don't think we need to think about testing lower than 1.4
