### ISSUE TITLE
Changes to Custom Set tests

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xgo#323]
We recently rewrote the test suite for Custom Set. Since this track implements Custom Set, please [take a look at the new custom_set.json file](https://github.com/exercism/x-common/blob/master/custom-set.json) and see if your track should update its implementation or tests.

The new test suite reorders tests so that students can get to green quickly. It also reduces the number of tests so that students can focus on solving the interesting edge cases.

More details on this change are available in [the pull request](https://github.com/exercism/x-common/pull/232)

**Comment by petertseng** [comment]
consolidate with #328 - they both are notifications for new tests, so they can both be done in the same go.
