### ISSUE TITLE
why is *.beam in gitignore

### ISSUE THREAD

**Issue by petertseng** [exercism/xgo#325]
I'm unsure of this one since when I see .beam I think erlang, but it's in the gitignore of many repositories (First discovered in https://github.com/exercism/xrust/pull/129#discussion_r64982860, also known to be in haskell ), so now I'm wondering

**Comment by kytrinyx** [comment]
I'm pretty sure it just accidentally happened at some point. A lot of the gitignores are probably a bit messy.
