### ISSUE TITLE
Updated tests for the Custom Set problem

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xgo#328]
In order to reduce the amount of code required to pass incremental tests (assuming that users pass tests starting from the top), the order of the tests was modified slightly.

Since this track implements Custom Set, please take a look at the new custom-set.json file and see if your track should update its tests.

If you do need to update your tests, please refer to this issue in your PR. That helps us see which tracks still need to update their tests.

If your track is already up to date, go ahead and close this issue.

More details on this change are available in https://github.com/exercism/x-common/pull/257.

**Comment by bordeltabernacle** [comment]
closed by #454
