### ISSUE TITLE
improper definition of the triangle inequality

### ISSUE THREAD

**Issue by matthewfischer** [exercism/xgo#334]
From the triangle problem:

> The sum of the lengths of any two sides of a triangle always exceeds the
> length of the third side, a principle known as the _triangle
> inequality_.

You are missing a key term of "or is equal to" there.

**Comment by matthewfischer** [comment]
I'd be happy to fix this but I cannot figure out where the README comes from, will dig.

**Comment by petertseng** [comment]
You got it correct that https://github.com/exercism/x-common/pull/298 is the place to fix it.

You are right that this is important because this track has tests for when they are equal.

Once that is merged, this will automatically be fixed for this track and all other tracks as well

**Comment by kytrinyx** [comment]
> You are missing a key term of "or is equal to" there.

There's a bit of a confusing technicality here :/

If the sides are equal, then the triangle is valid... but degenerate.
