### ISSUE TITLE
Go: Specifications confusing (closes exercism/exercism.io/issues/2746)

### ISSUE THREAD

**Issue by Insti** [exercism/xgo#338]
I found this issue in the main exercism.io repository which applies to the go track:
https://github.com/exercism/exercism.io/issues/2746
Can someone from the Go team evaluate it, thanks.

**Comment by petertseng** [comment]
My evaluation is: Since this deals with the README, this is not specific to Go, so should be moved to https://github.com/exercism/x-common/issues/321
