### ISSUE TITLE
how to make "exercism fetch go" place files in go path instead of home directory?

### ISSUE THREAD

**Issue by muly** [exercism/xgo#341]
Right now the fetch command is placing the exercise files in my home directory, and because of that I'm not able to conveniently run the go install. any thought on workaround or fix?

**Comment by muly** [comment]
I can move the exercise folder to GOPATH, but then the `exercism submit` doesn't work. 

I found a way to change this exercise directory configuration. I ran the below command to reconfigure the exercise directory to point to the folder in Go Path. and I'm good now.
`exercism configure --dir=GO_PATH/src/exercism`

**Comment by kytrinyx** [comment]
@muly glad you sorted it out. The solution you found is the one we'd have suggested, too.
