### ISSUE TITLE
crypto-square examples have trailing spaces stripped, not in README

### ISSUE THREAD

**Issue by matthewfischer** [exercism/xgo#348]
The crypto-square examples and directions do not mention that trailing spaces should be stripped. It instead requires perfect squares which should include trailing spaces. This should be fixed in the README for example, the splunk example should be:

"s-u- "
"p-n- "
"l-k- "

However the output requires no space after the lk pair. This issue is repeated in other ones as well.

**Comment by kytrinyx** [comment]
Thanks @matthewfischer, I expect that this is a problem that affects all the language tracks. Would you mind opening this issue in https://github.com/exercism/x-common/issues so that everyone involved can hash out the details of the fix?

**Comment by matthewfischer** [comment]
Done, moved to https://github.com/exercism/x-common/issues/356.

**Comment by kytrinyx** [comment]
Thank you :heart:
