### ISSUE TITLE
[series]: what are the (Unsafe)First tests for?

### ISSUE THREAD

**Issue by NobbZ** [exercism/xgo#360]
As far as I can tell, the function `All` does pretty much whats ask for in the README, but there are tests asking for two unrelated functions, that I do not see to use in `All` at all, so what are these tests for?

As an example I give my solution:

http://exercism.io/submissions/505c72c7392340ffb17bfd2c1f5907ec

**Comment by petertseng** [comment]
I see. It looks like the relevant rationale is in #72 from a liberal interpretation of the README:

> It shows a list of all series

So this is why we have `All`

> and then it says if you ask for **a** 6-digit..., implying a single result

So this is why we have `First`.

> Of course we want people to learn out-of-band signaling, starting with Go's `, ok`

And thus, it became `UnsafeFirst` and `First`

Interesting progression. I'm suspending judgment on whether it *should* be that way; this comment only says why it is.

**Comment by NobbZ** [comment]
I think I do understand. Thank you.
