### ISSUE TITLE
Acronym example

### ISSUE THREAD

**Issue by Akasurde** [exercism/xgo#382]

**Comment by alebaffa** [comment]
Hi, in this exercise the function to test `abbreviate` is not capital letter. In all the other Go exercises they were so. It's true that the tests are always in the same package of the code, so in general having an exported function is not strictly necessary, but still this exercise goes against the convention used so far.
Should we fix it?

**Comment by petertseng** [comment]
I assume so, because I think we want to export all the functions under test, as a matter of style. We can question this assumption, but the README says "In general, adding tests for unexported names is considered an anti-pattern" so it seems like this is what is decided.
