### ISSUE TITLE
gigasecond: not compile, raise errors

### ISSUE THREAD

**Issue by dvrkps** [exercism/xgo#385]
# github.com/exercism/xgo/exercises/gigasecond
./gigasecond.go:5: syntax error: illegal character U+003F '?'
./gigasecond.go:8: syntax error: unexpected AddGigasecond, expecting (
./gigasecond.go:11: testVersion redeclared in this block
	previous declaration at ./example.go:5
FAIL	github.com/exercism/xgo/exercises/gigasecond [build failed]

**Comment by petertseng** [comment]
This is OK since this is the stub file served to students to get them started. We coul dmake it compile by changing the `?` to an actual value if we like.
