### ISSUE TITLE
docs: SETUP.md is outdated

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/xgo#417]
Simply running `go test` isn't enough anymore, document needs to be updated about exercises with stubs and how to use scripts under `bin`.

**Comment by petertseng** [comment]
This is slightly confusing right now - SETUP.md is what is delivered as part of the README.md to each student solving a particular exercise, not for contributors of the track

We want to change it to TRACK_HINTS.md as of https://github.com/exercism/discussions/issues/95 and https://github.com/exercism/exercism.io/issues/3240 , but it it not implemented yet. When it is, then we will be able to rename SETUP.md

**Comment by ferhatelmas** [comment]
Ah, I was actually wondering why it wasn't mentioned there even if it's written in readme. Clear now. 

Should we keep it open until this change is implemented or close ?

**Comment by petertseng** [comment]
Let's close for now since we can't take any actions yet. When the change gets implemented, one of the steps at https://github.com/exercism/exercism.io/issues/3240 is to open an issue on every track, so we can trust that they will open one in this track when we can actually act.
