### ISSUE TITLE
Verify contents and format of track documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#424]
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

**Comment by petertseng** [comment]
This language track has these docs:

* How to install: https://github.com/exercism/xgo/blob/master/docs/INSTALLATION.md, appearing at http://exercism.io/languages/go/installing
* How to install dependences: We avoid external dependencies, and our test runner `go test` comes with Go.
* How to run the tests: https://github.com/exercism/xgo/blob/master/docs/TESTS.md, appearing at http://exercism.io/languages/go/tests
* Introduction: https://github.com/exercism/xgo/blob/master/docs/ABOUT.md, appearing at http://exercism.io/languages/go/about
* Where learn: https://github.com/exercism/xgo/blob/master/docs/LEARNING.md, appearing at http://exercism.io/languages/go/learning
* Resources: https://github.com/exercism/xgo/blob/master/docs/RESOURCES.md, appearing at http://exercism.io/languages/go/resources

Finally, we have no images in any of the docs in the `docs` directory (we do have images in our README.md, but those are not displayed on the website).

Given the above information, I claim that this track meets the basic requirements set out in this issue.

Of course, anyone reading is free to help us improve our documentation. The above assertion that we meet the basic requirements doesn't necessarily mean that all the docs are perfect and never need changes again.
