### ISSUE TITLE
grains: note regarding using bitwise operations

### ISSUE THREAD

**Issue by bordeltabernacle** [exercism/xgo#431]
There are two approaches to this problem, bitwise operations and using `math.Pow()`.

Maybe a note could be added to the test file about taking a bitwise approach, with some links to what bitwise operations are. In a similar way to the way the house exercise suggests the use of recursion but allows a simpler approach.

Then, should the difficulty rating in the `config.json` file stay with the simpler approach, or the more challenging approach?

**Comment by petertseng** [comment]
It may be good to ask the maintainers of other tracks as well, to see what their experience is with this. My guess is that we should try to guess what a "typical" student would do. I know that being human our guesses are prone to be fallible, but we can always adjust if we find out a guess is wrong.

**Comment by bordeltabernacle** [comment]
OK, that sounds good, I think I'll open up an issue in discussions to get some more feedback on this. And I'll have a look into adding something to grains about the potential for bitwise operators. It's a topic I personally don't understand yet, and I feel may provide a good introduction for others in the same boat. I'll submit a PR, let me know what you think?
