### ISSUE TITLE
No multibyte rune in hamming problem

### ISSUE THREAD

**Issue by usmanismail** [exercism/xgo#441]
In the [hamming problem](https://github.com/exercism/xgo/tree/master/exercises/hamming) the test cases are limited to single byte runes. While this makes sense in the context of DNA nucleotides it does hide the fact that range on string does not return character values. Maybe a slightly modified problem and/or test cases with multi-byte runes would be a useful addition here.

**Comment by petertseng** [comment]
I do think it is a good idea to expose students to the difference between iterating over a string (gives runes) versus indexing into a string (gives bytes).

The current situation in x-common, where we generally agree on which test cases should go in each exercise no matter the language, is at https://github.com/exercism/x-common/issues/428 where we say we keep the existing exercises ASCII-only.

For this track, we have several possibilities for what to do:

* Convince track-maintainers of various tracks at x-common that the decision should be changed
* Add multi-byte runes to Go's hamming test cases anyway, in contravention of the decision made (we would need a compelling reason to go against x-common)
* Create a new exercise (as suggested by https://github.com/exercism/x-common/issues/455), implement it for the Go track, and use it to show the considerations involved with multi-byte runes.

**Comment by usmanismail** [comment]
Closing in favor of other issues will comment there if needed.
