### ISSUE TITLE
Luhn tests missing coverage for common mistake (right vs left)

### ISSUE THREAD

**Issue by michaelorr** [exercism/xgo#500]
From the README:
`The first step of the Luhn algorithm is to double every second digit,
starting from the right. ...`

This distinction about right versus left isn't super obvious at first glance. The first example contains odd number of total digits, so every 2nd digit from the **_right_** is the same as every 2nd digit from the **_left_**.
When I got to the later examples, I thought that the README had a typo.
My implementation doubled every 2nd digit from the **_left_** (incorrect) but the test suite did not catch my mistake.

I was working on a PR to update what I thought to be a typo in the readme when I realized my mistake. I think the readme is clear enough, it was my mistake in reading it incorrectly.
I think a new test case should be added where modifying every 2nd digit from the **_right_** is a valid Luhn number as expected but modifying every 2nd digit from the **_left_**  is not a valid Luhn number. Devising such a number should not be too difficult.

**Comment by michaelorr** [comment]
Hopefully I'll have a little spare time this evening to add this test case.

**Comment by petertseng** [comment]
Excellent explanation, thanks. We added the case "59", with an even number of digits, in https://github.com/exercism/x-common/pull/522. We want to add it to this track soon, depending on what happens in https://github.com/exercism/x-common/issues/523. The work for this track is in progress at #479 so follow along if you are interested.

**Comment by stkent** [comment]
Hopefully https://github.com/exercism/x-common/pull/549, now merged, will also help with this!

**Comment by michaelorr** [comment]
@stkent I'll take a look today. Thank you!

**Comment by michaelorr** [comment]
https://github.com/exercism/x-common/pull/549 absolutely helps clarify the readme, thanks!
And https://github.com/exercism/xgo/pull/479 adds the test case `59` which would have caught my bug.
It looks like https://github.com/exercism/xgo/pull/479 is being held up by https://github.com/exercism/x-common/issues/523 and https://github.com/exercism/x-common/pull/547. Is there anything I could do to help move those along? 547 looks like it may be ready for merge.

**Comment by stkent** [comment]
As far as I'm concerned, 547 is indeed good to merge. If/when 523 is resolved one way or the other, we'd still want the extra positive tests added in 547. If you are willing to review and/or merge 547, I'd appreciate it!

**Comment by petertseng** [comment]
Closed by #479
