### ISSUE TITLE
Document test consistency setup in hello-world

### ISSUE THREAD

**Issue by tleen** [exercism/xgo#515]
Spawning off of the discussion in #470: add more commentary to the [hello-world exercise](https://github.com/exercism/xgo/tree/master/exercises/hello-world) to make it clear to new users the test consistency boilerplate that is (or will be after #470 is done) present in all the golang exercises.

**Comment by tleen** [comment]
Via #507 don't forget to remove the redundant commentary in error-handling and wherever else it is present.

**Comment by tleen** [comment]
Commentry also present in [leap](https://github.com/exercism/xgo/blob/master/exercises/leap/leap.go#L6).

**Comment by robphoenix** [comment]
commentary also present in paasio
