### ISSUE TITLE
Remove the term "nitpick"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#516]
We've been moving away from the term "nitpick" and its variants ("nitpicker", "nitpicking", etc), as some people have visceral and very negative associations with it.

We've tried to move the terminology towards that of _conversation_. Comment is good (if somewhat bland). Feedback is OK, though it suggests that people only comment in order to give feedback, which can be unnecessarily restricting.

I noticed this in the stub comments in [hello-world](https://github.com/exercism/xgo/blob/master/exercises/hello-world/hello_world.go).

I did a grep in the project, and there's nothing else in master, currently, that mentions _nitpick_, however I did not check open issues and PRs.

**Comment by robphoenix** [comment]
Is there an accepted term to replace *"nitpicker(s)"*? student(s)? people?

**Comment by stkent** [comment]
"reviewers"?

**Comment by petertseng** [comment]
We could go with something really generic like "readers of the code", but that may be too long. 

"Reviewers" is good - seems to capture well the role of someone reading the code. It has precedent too.

* http://exercism.io/: "The solutions you write provide reviewers with clues about..." "Each solution you review challenges you..."
* https://github.com/exercism/xgo/blob/master/exercises/clock/clock.go#L26
* https://github.com/exercism/xgo/blob/master/exercises/gigasecond/gigasecond.go#L10

I know I say student, but I can't pretend the term is universal. In this context it might also cause the student to think "so does that mean I'm the teacher?"
