### ISSUE TITLE
recommendations for function comments

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#552]
According to the rules of Go, exported functions should have comments, but they are not necessary for Exercism exercises, and most submissions do not include them.

In [hello-world](https://github.com/exercism/xgo/blob/master/exercises/hello-world/hello_world.go) we say:

> HelloWorld needs a comment documenting it as package does.

and

> Package greeting should have a package comment that summarizes what it's about.

Should we change this to a recommendation for what is good Go practice, but that for these exercises they're not necessary? 

Similar to what is currently in `leap`:

>  It's good style to write a comment here documenting IsLeapYear.

We're not going to enforce comments and it's up to each individual how they want to approach these exercises; as a way to practice writing code, or as a way to build a habit of best practices.

**Comment by tleen** [comment]
It makes a comment to add to a user's early submissions. [It made an impression on me!](http://exercism.io/submissions/227fff0ab4c1435ea3fe2ad4f1a5ea91) 

 Ignoring comments is not technically incorrect but at the same time _Doing Things The Right Way_ seems to be embedded in the culture of Go so encouraging comments is also good. Go is one of those rare languages where getting things culturally correct is as important as getting it technically correct. It's one of the reasons I like it!

Perhaps this is a good thing to make part of an automated review. Is this the sort of thing [Rikki](https://github.com/exercism/rikki) can do?

**Comment by robphoenix** [comment]
What a great start to Go & exercism! :smiley: 

I don't want to discourage comments, but I do wonder if we should make the distinction between what will make the tests pass and what is recommended good practice, leaving the choice of comments up to the user. 

Personally I don't bother with comments in my exercism exercises, but I make sure I have them in my other code.

I feel that rather than saying that an exported function `needs a comment` (it doesn't to make the tests pass) it should maybe be an advisory, such as `it is good practice to comment all your exported functions, and golint will complain if you don't` or something much better?

**Comment by petertseng** [comment]
I forget whether we `golint` all of the Go submissions - I know we certainly `go vet` them all... okay, checked quickly, we don't `golint`. I suppose we could (add to https://github.com/exercism/rikki/blob/master/analysis/golang/golang.go ) though we may have to do some filtering on the things golint sees. I think golint still has a few things to say about this repo's code as well.

Sometimes when I see text warning me "X is necessary", I get the temptation to remove X and see what happens. And if I see that nothing happens (or seems to happen) maybe I'll have less faith in comments that say "X is necsesary". So this is all about precision of wording, I guess. I'm all for saying "It's good style to have comments" rather than "You *need* to have comments".

We can explain that go doc will automatically extract the documentation, maybe link to https://blog.golang.org/godoc-documenting-go-code. This tells about the cultural aspect plus the tool assistance.

**Comment by tleen** [comment]
Golinting the entire repo is probably a good idea, although like #470 any repo wide update will take a while.  I think it is worth emphasising the cultural aspects of golang in the track.

**Comment by robphoenix** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [recommendations for function comments](https://trello.com/c/26Dzzuk8/2-recommendations-for-function-comments)

**Comment by tleen** [comment]
@robphoenix I get an error accessing that link:
> This card may be on a private board. You may be able to view it by logging in.

**Comment by robphoenix** [comment]
Ah, sheesh, I didn't realise it had done that, ignore it, it's just me organising my life, sorry!

**Comment by tleen** [comment]
:smile: np, I was thinking of moving on to linting all the exercises soon, one at a time, just like #470.

**Comment by robphoenix** [comment]
I wondered if it would be good to automate something like that, so that it doesn't become something that gets easily out of sync.
I used the following script in the root of the repo:

```sh
for d in exercises/*/ ; do                                                                                                                 
     golint ./$d | grep -v comment                                                                                                          
done
```

This ignores any golint complaints that are about comments, which is nearly all of them, the rest is:

```sh                                                                                                                         [127]
exercises/clock/clock.go:14:12: expected type, found newline (and 1 more errors)
exercises/gigasecond/gigasecond.go:5:21: illegal character U+003F '?' (and 1 more errors)
exercises/palindrome-products/example.go:50:20: error strings should not be capitalized or end with punctuation or a newline
exercises/roman-numerals/example.go:19:25: error strings should not be capitalized or end with punctuation or a newline
exercises/triangle/triangle.go:9:10: expected type, found newline (and 1 more errors)
```

It's perhaps worth moving this into a new issue?
