### ISSUE TITLE
status of accumulate, strain & list-ops

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#555]
`accumulate` & `strain` are to be deprecated across the exercism curriculum, in favour of the `list-ops` exercise:

https://github.com/exercism/xjava/issues/297
https://github.com/exercism/x-common/issues/553#issuecomment-279275406
https://github.com/exercism/x-common/issues/588#issuecomment-279275431

Currently in this track `accumulate` is deprecated, `strain` is active and `list-ops` has not been implemented.

There has been some recent discussion about this [here](https://github.com/exercism/xgo/issues/18#issuecomment-283222291)
The main points being:

* Although list operations such as map, filter and reduce are actively discouraged in Go, it is still considered a beneficial learning exercise to implement them, though for a specific type rather than generically.
* The suggestion that this track un-deprecate `accumulate`, until `list-ops` is added. If list-ops will be added within the next few days, then there's no point in adding the churn, but if it will be a while in coming, why not show accumulate?

I'd like to implement the `list-ops` exercise but realistically am not going to within the next few days. Please don't take this as my calling dibs on the exercise, I am sure others would probably implement it better than me and from my point of view it would be an opportunity for learning rather than a doubling of efforts.

So, until `list-ops` is implemented do we:

1. deprecate `strain` and un-deprecate `accumulate`
2. leave `strain` and un-deprecate `accumulate`
3. leave both as is until `list-ops` is implemented and then deprecate `strain`

**Comment by petertseng** [comment]
In case I haven't made it clear by my https://github.com/exercism/xgo/issues/18#issuecomment-283488655, I suggest to un-deprecate `accumulate`. We can deprecate them when `list-ops` comes.

**Comment by robphoenix** [comment]
Ok, well, unless there's any objections, let's do that. @ferhatelmas @tleen
