### ISSUE TITLE
Example tests are not fetched by the exercism client

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#621]
We recently added example tests to this track, #420, #568, however it's been overlooked that because they have the word `example` in the filename these example tests are not being fetched by the exercism client.

I'm not sure where the constraint for this is located within the exercism codebase, so don't know about a solution that could allow us to keep these files named as they are.

Otherwise we can just name them something else, or move the example tests into the main test files, and they'll still run.

**Comment by petertseng** [comment]
> where the constraint for this is located within the exercism codebase

https://github.com/exercism/trackler/blob/master/lib/trackler/implementation.rb#L9

**Comment by robphoenix** [comment]
ah, ok, thanks @petertseng 

Ideally it would be good to keep the example tests in a separate file named `example_test.go` as this appears to be the convention used in the language. This would mean changing the above regex to something like `example(?!_test)` (see https://regex101.com/r/ifNpuG/1). I don't know what unintended side effects on other languages this would have. Do you know @petertseng @kytrinyx? Would it be worthwhile opening an issue regarding this in the trackler or discussions repos?

If we can't go this route then we have these two options:

- use a different filename, for instance `sample_test.go` or `ex_test.go` (these are not good, I know, purely illustrative) which is problematic because it introduces a convention that is exercism specific, not Go specific.
- keep them in the standard test file `<exercise>_test.go`, which is preferable, but in exercises where there are example tests alongside the standard tests, currently only `hello-world` and `clock`, this could make those test files rather long, though this is not a problem for any future exercises that only have example tests.

**Comment by kytrinyx** [comment]
We can use a custom regex in the `config.json` file at the root of the repository.

https://github.com/exercism/request-new-language-track/blob/master/config.json#L6

**Comment by robphoenix** [comment]
Ah, amazing, thanks @kytrinyx. I assume that regex isn't a complete replacement for the one in Trackler, so in the `config.json`, should it be the filename, ie `example_test` or `example_*_test`? Does it need the file extension?

**Comment by kytrinyx** [comment]
@robphoenix The regex is a complete replacement for the one in Trackler. If the config has a regex, then we use it. If not, we fall back to `/test/i`.

It doesn't add any further restrictions at the boundaries (unless the regex in the config does), so you can leave the extension off if you want.

Not all tests will have `example` in them, so you'd need a regex that handles both example_tests and other tests.

**Comment by robphoenix** [comment]
Sorry, but I think I'm a little confused.  

I was thinking of the regexes linked to by @petertseng here: https://github.com/exercism/trackler/blob/master/lib/trackler/implementation.rb#L9

```ruby
    IGNORE = [
      Regexp.new("HINTS\.md$"),
      Regexp.new("example", Regexp::IGNORECASE),
      Regexp.new("\/\.$"),
      Regexp.new("/\.meta/")
    ]
```

but you're referring to this regex, right?https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb#L78

```ruby
    def test_pattern
      if config.key?('test_pattern')
        Regexp.new(config['test_pattern'])
      else
        /test/i
      end
    end
```

Does one override the other? As in, if we define a `test_pattern` regex, (say `/\w+_test/i`) will everything matching it then not be ignored? But then the current regex `/test/i` should cover `example_test.go` shouldn't it? But it's still ignored because of the `IGNORE` array?
So is it then that anything with `example` in it is ignored after the `test_pattern` has been matched, and so the `test_pattern` regex is redundant as files with `example` will still be ignored no matter what the `test_pattern` is? 

I've had a look through the Trackler, exercism.io & x-api code, but I don't know Ruby (not much of an excuse though) and I couldn't figure out how a filename passes through the `test_pattern` regex and the list of regexes to ignore (does that make sense?)

I feel like I'm being really dense here, but I think in this case I'm going to need it explaining to me like I'm 5! Sorry, if I'm missing the obvious.

**Comment by kytrinyx** [comment]
> if we define a test_pattern regex, (say /\w+_test/i) will everything matching it then not be ignored?

Ooooooh. Sorry. I'm an idiot.

The answer is I have no idea, I will have to write a test to make sure that if it matches the test_pattern then it will never be ignored.

**Comment by kytrinyx** [comment]
OK, verified. You are absolutely correct. If it's in the ignore pattern, it is unconditionally ignored, whether or not it matches the test pattern.

I'm going to make that change.

**Comment by kytrinyx** [comment]
OK, PR open here: https://github.com/exercism/trackler/pull/32

**Comment by robphoenix** [comment]
Amazing, thanks @Insti & @kytrinyx you both rock! :guitar: I'll open a PR to close this today.

**Comment by robphoenix** [comment]
closed by #645

**Comment by robphoenix** [comment]
I've just tried an `exercism fetch go --all` with an empty exercism directory and the current master branch of the cli and the example tests are still not being fetched.

**Comment by Insti** [comment]
Have the changes been deployed yet?

**Comment by robphoenix** [comment]
Ok, cool. Thanks for looking into this @Insti, I appreciate it.

**Comment by petertseng** [comment]
http://x.exercism.io/v2/exercises/go/hello-world contains example_hello_world.go

**Comment by petertseng** [comment]
sigh, I obviously meant example_helloworld_test.go
