### ISSUE TITLE
bob: ensure generator is up-to-date

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#624]
Parent issue: #604

Because of recent changes to make all the canonical-data.json files conform to
a common scheme (https://github.com/exercism/x-common/issues/625), it might be
the case that our current generator no longer runs.

For this exercise we need to make sure the current generator runs, and if it
doesn't then we need to update it.

In addition, the three lines at the top of the file:

```
// Source: {{.Ori}}
{{if .Commit}}// Commit: {{.Commit}}
{{end}}
```

can simply be replaced with `{{.Header}}`, which has the effect of:

* Deprecating the `Ori` field, which is confusingly named
* Showing the x-common version in the test file
* Reducing duplicate code

**Comment by leenipper** [comment]
For the bob exercise, this x-common commit: https://github.com/exercism/x-common/commit/45ff2e03840365ca5f8a3e7a09ac7d1558039972 removed two test cases which had umlauts in the test data. There wasn't much justification, just that non-Latin characters were removed.

I was debating whether to manually insert those test cases back with lines in the template after the canonical-data.json generated cases. I think the umlauts fit well with Go supporting UTF-8. Other opinions on this ?

**Comment by petertseng** [comment]
The justification is https://github.com/exercism/x-common/issues/441

I don't really care, but I do note I don't think they add much value, in the sense of - I don't think we are likely to see implementations that would fail the umlaut test. I wonder if I am proven wrong by some data somewhere.

**Comment by robphoenix** [comment]
Personally I agree with the discussion in https://github.com/exercism/x-common/issues/428 and would prefer to stick with the canonical-data. I worry also that this might undermine the benefit of the generators by creating test data that has specific manual upkeep, rather than relying on the canonical-data.json.
It would be good to see some exercises deal with non-ASCII specifically.

**Comment by robphoenix** [comment]
for reference: https://github.com/exercism/xgo/issues/195#issuecomment-153033299

**Comment by leenipper** [comment]
OK, very good. Using canonical-data.json is best.
