### ISSUE TITLE
meetup: ensure generator is up-to-date

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#636]
Parent issue: #604

Because of recent changes to make all the canonical-data.json files conform to
a common scheme (https://github.com/exercism/x-common/issues/625), it might be
the case that our current generator no longer runs.

For this exercise we need to make sure the current generator runs, and if it
doesn't then we need to update it.

In addition, the three lines at the top of the file:

```
// Source: {{.Ori}}
{{if .Commit}}// Commit: {{.Commit}}
{{end}}
```

can simply be replaced with `{{.Header}}`, which has the effect of:

* Deprecating the `Ori` field, which is confusingly named
* Showing the x-common version in the test file
* Reducing duplicate code

**Comment by leenipper** [comment]
Closed by #647
