### ISSUE TITLE
Tests for exercise 'transpose' pass when they should fail

### ISSUE THREAD

**Issue by tapank** [exercism/xgo#651]
For the following implementation of transpose, the tests pass while they are expected to fail.

```
package transpose

const testVersion = 1

func Transpose(m []string) []string {
	return []string{}
}
```

**Comment by tapank** [comment]
I have a fix for this issue and will try to submit a pull request shortly.

**Comment by petertseng** [comment]
Nice find.

If we wished to rigourously test for this, a possibility would be to add example solutions that are expected to fail the tests, and test in Travis CI that they do in fact fail.
