### ISSUE TITLE
Test fail messages

### ISSUE THREAD

**Issue by soniakeys** [exercism/xgo#88]
Not a bug, but there's an interesting [thread on go-nuts](https://groups.google.com/d/topic/golang-nuts/DEJ0qjuB3KE/discussion) relevant for us where we want to display where returned results differ from wanted results.  We use a mix of ad-hoc techniques currently.  At some point we might want to try something like what they are talking about in this thread, maybe for consistent output, maybe to improve messages, maybe to help test program correctness or readability.

**Comment by petertseng** [comment]
It seems most test messages are reasonable in this track - any actions to be taken here? If not let's close this one. But obviously discussion is welcomed if there are specific exercises with improvable test messages (such as in #317)

**Comment by kytrinyx** [comment]
Yeah, I think we're fine in general. Thanks!
